### ISSUE TITLE
Can't install requirements.txt

### ISSUE THREAD

**Issue by Axrxaxra** [asharbinkhalil/gumshoe#2]
After trying to install "... requirements.txt" , it says : No such file or directory: 'requirements.txt'
You said that We should xopy the repository, but where from?
And what is the API? What does mean code in that link?

**Comment by asharbinkhalil** [comment]
if you are in the right directory where requiremets.txt is, it should work

**Comment by asharbinkhalil** [comment]
for the api keys file, i meant to add tokens or apis if you have, because the github module works by providing token
